# Generated by Django 5.0 on 2023-12-09 13:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="thumbnail",
            field=models.ImageField(blank=True, default="default.png", upload_to=""),
        ),
    ]
